name: CI Pipeline

on:
  push:
    branches:
      - main
      - aditya_dev  # You can specify any branch you want to run the CI for
  pull_request:
    branches:
      - main
      - aditya_dev  # Run tests on PRs made to these branches

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # You can change the Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
